# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c342483e0a09ec3b7b673d89596296d1cabcea38fe880f7515f895244b920829e1887080ed9f1e330aabedb69f60c587a888c0b1029cdfff934ba63ad94a2788

test:
  secret_key_base: 12a95f16a6ec47295caef1511d1f9deb3a9018eb51c4f14825fc1269abe7a144c078921ca9e44417868e8501eb6e763e9a567e410dbb9afa7d3836078ff73e07

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
